services:
  spark-master:
    image: apache/spark:3.5.3
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - ./apps:/opt/spark/apps
      - ./data:/opt/spark/data

  spark-worker:
    image: apache/spark:3.5.3
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    ports:
      - "8082:8081"
    volumes:
      - ./apps:/opt/spark/apps
      - ./data:/opt/spark/data
    depends_on:
      - spark-master

